// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AlteracaoDeSenhaFeature : object, Xunit.IClassFixture<AlteracaoDeSenhaFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AlterarSenha.feature"
#line hidden
        
        public AlteracaoDeSenhaFeature(AlteracaoDeSenhaFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Alteração de Senha", "  Como um funcionário do sistema\r\n  Eu quero alterar minha senha\r\n  Para manter m" +
                    "inha conta segura", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Alterar senha com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Alterar senha com sucesso")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void AlterarSenhaComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alterar senha com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "aAtual@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 10
    testRunner.And("que o funcionário está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "SenhaAtual",
                            "NovaSenha"});
                table1.AddRow(new string[] {
                            "SenhaAtual@123",
                            "NovaSenha@456"});
#line 11
    testRunner.When("o funcionário solicita alteração de senha informando:", ((string)(null)), table1, "Quando ");
#line hidden
#line 14
    testRunner.Then("a senha deve ser alterada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 15
    testRunner.And("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.And("a nova senha deve estar hasheada no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não deve alterar senha quando senha atual está incorreta")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Não deve alterar senha quando senha atual está incorreta")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void NaoDeveAlterarSenhaQuandoSenhaAtualEstaIncorreta()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não deve alterar senha quando senha atual está incorreta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "aAtual@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 21
    testRunner.And("que o funcionário está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "SenhaAtual",
                            "NovaSenha"});
                table2.AddRow(new string[] {
                            "SenhaErrada123",
                            "NovaSenha@456"});
#line 22
    testRunner.When("o funcionário solicita alteração de senha informando:", ((string)(null)), table2, "Quando ");
#line hidden
#line 25
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 26
    testRunner.And("o sistema deve retornar mensagem \"Current password is incorrect\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 27
    testRunner.And("a senha não deve ser alterada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não deve alterar para senha vazia")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Não deve alterar para senha vazia")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void NaoDeveAlterarParaSenhaVazia()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não deve alterar para senha vazia", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 31
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "aAtual@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 32
    testRunner.And("que o funcionário está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "SenhaAtual",
                            "NovaSenha"});
                table3.AddRow(new string[] {
                            "SenhaAtual@123",
                            ""});
#line 33
    testRunner.When("o funcionário solicita alteração de senha informando:", ((string)(null)), table3, "Quando ");
#line hidden
#line 36
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 37
    testRunner.And("o sistema deve retornar mensagem \"Nova senha é obrigatória\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 38
    testRunner.And("a senha não deve ser alterada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não deve alterar para senha fraca")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Não deve alterar para senha fraca")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void NaoDeveAlterarParaSenhaFraca()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não deve alterar para senha fraca", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 42
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "aAtual@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 43
    testRunner.And("que o funcionário está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "SenhaAtual",
                            "NovaSenha"});
                table4.AddRow(new string[] {
                            "SenhaAtual@123",
                            "123"});
#line 44
    testRunner.When("o funcionário solicita alteração de senha informando:", ((string)(null)), table4, "Quando ");
#line hidden
#line 47
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 48
    testRunner.And("o sistema deve retornar mensagem indicando que a senha não atende aos critérios d" +
                        "e segurança", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 49
    testRunner.And("a senha não deve ser alterada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não deve alterar para mesma senha atual")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Não deve alterar para mesma senha atual")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void NaoDeveAlterarParaMesmaSenhaAtual()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não deve alterar para mesma senha atual", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 53
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "aAtual@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 54
    testRunner.And("que o funcionário está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "SenhaAtual",
                            "NovaSenha"});
                table5.AddRow(new string[] {
                            "SenhaAtual@123",
                            "SenhaAtual@123"});
#line 55
    testRunner.When("o funcionário solicita alteração de senha informando:", ((string)(null)), table5, "Quando ");
#line hidden
#line 58
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 59
    testRunner.And("o sistema deve retornar mensagem \"Nova senha deve ser diferente da atual\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 60
    testRunner.And("a senha não deve ser alterada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não deve alterar senha de funcionário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Não deve alterar senha de funcionário inexistente")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        public void NaoDeveAlterarSenhaDeFuncionarioInexistente()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "autenticacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não deve alterar senha de funcionário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 64
    testRunner.Given("que não existe funcionário com ID \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 65
    testRunner.When("é solicitada alteração de senha do funcionário inexistente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 66
    testRunner.Then("o sistema deve retornar status 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 67
    testRunner.And("o sistema deve retornar mensagem \"Employee with ID \'99999999-9999-9999-9999-99999" +
                        "9999999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não deve alterar senha sem autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Não deve alterar senha sem autenticação")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        public void NaoDeveAlterarSenhaSemAutenticacao()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "autenticacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não deve alterar senha sem autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 71
    testRunner.Given("que existe um funcionario cadastrado com email \"usuario@supply.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 72
    testRunner.And("que o usuário não está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 73
    testRunner.When("o usuário tenta alterar a senha sem autenticação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 74
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 75
    testRunner.And("o sistema deve retornar mensagem \"Não autorizado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Alteração de senha deve gerar evento de domínio")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Alteração de senha deve gerar evento de domínio")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "seguranca")]
        public void AlteracaoDeSenhaDeveGerarEventoDeDominio()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "seguranca"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alteração de senha deve gerar evento de domínio", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 79
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "aAtual@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 80
    testRunner.And("que o funcionário está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "SenhaAtual",
                            "NovaSenha"});
                table6.AddRow(new string[] {
                            "SenhaAtual@123",
                            "NovaSenha@456"});
#line 81
    testRunner.When("o funcionário solicita alteração de senha informando:", ((string)(null)), table6, "Quando ");
#line hidden
#line 84
    testRunner.Then("a senha deve ser alterada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 85
    testRunner.And("o evento PasswordChangedEvent deve ser disparado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deve invalidar sessões anteriores após alteração de senha")]
        [Xunit.TraitAttribute("FeatureTitle", "Alteração de Senha")]
        [Xunit.TraitAttribute("Description", "Deve invalidar sessões anteriores após alteração de senha")]
        [Xunit.TraitAttribute("Category", "senha")]
        [Xunit.TraitAttribute("Category", "alterar")]
        [Xunit.TraitAttribute("Category", "seguranca")]
        public void DeveInvalidarSessoesAnterioresAposAlteracaoDeSenha()
        {
            string[] tagsOfScenario = new string[] {
                    "senha",
                    "alterar",
                    "seguranca"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deve invalidar sessões anteriores após alteração de senha", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 89
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "aAtual@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 90
    testRunner.And("que o funcionário possui sessões ativas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 91
    testRunner.When("o funcionário altera sua senha com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 92
    testRunner.Then("todas as sessões anteriores devem ser invalidadas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 93
    testRunner.And("apenas a sessão atual deve permanecer válida", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AlteracaoDeSenhaFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AlteracaoDeSenhaFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
