// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AtualizacaoDeFuncionarioFeature : object, Xunit.IClassFixture<AtualizacaoDeFuncionarioFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AtualizarFuncionario.feature"
#line hidden
        
        public AtualizacaoDeFuncionarioFeature(AtualizacaoDeFuncionarioFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Atualização de Funcionário", "  Como um usuário autorizado do sistema\r\n  Eu quero atualizar os dados de funcion" +
                    "ários\r\n  Para manter as informações atualizadas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário com dados válidos")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário com dados válidos")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void AtualizarFuncionarioComDadosValidos()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário com dados válidos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 10
    testRunner.And("que existe um funcionário cadastrado com ID conhecido e nome \"João Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Telefones"});
                table7.AddRow(new string[] {
                            "João",
                            "Oliveira",
                            "joao.oliveira@supply.com",
                            "11999999999,11888888888"});
#line 11
    testRunner.When("o usuário atualiza o funcionário com:", ((string)(null)), table7, "Quando ");
#line hidden
#line 14
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 15
    testRunner.And("o sistema deve retornar os dados atualizados do funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.And("o funcionário no banco de dados deve ter os novos dados salvos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário inexistente")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void AtualizarFuncionarioInexistente()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 21
    testRunner.And("que não existe funcionário com ID \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 22
    testRunner.When("o usuário tenta atualizar o funcionário inexistente com dados válidos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 23
    testRunner.Then("o sistema deve retornar status 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 24
    testRunner.And("o sistema deve retornar mensagem \"Employee \'Funcionário não encontrado\' was not f" +
                        "ound\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário sem autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário sem autenticação")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        public void AtualizarFuncionarioSemAutenticacao()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "autenticacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário sem autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 28
    testRunner.Given("que o usuário não está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 29
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 30
    testRunner.When("o usuário tenta atualizar o funcionário com dados válidos sem autenticação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 31
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 32
    testRunner.And("o sistema deve retornar mensagem \"Não autorizado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 33
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário com documento duplicado de outro funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário com documento duplicado de outro funcionário")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "conflito")]
        public void AtualizarFuncionarioComDocumentoDuplicadoDeOutroFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "conflito"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário com documento duplicado de outro funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 37
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 38
    testRunner.And("que existe um funcionário com ID conhecido e documento \"11111111111\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 39
    testRunner.And("que existe outro funcionário com documento \"22222222222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 40
    testRunner.When("o usuário tenta atualizar o funcionário para documento \"22222222222\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 41
    testRunner.Then("o sistema deve retornar status 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 42
    testRunner.And("o sistema deve retornar mensagem \"Documento já cadastrado para outro funcionário\"" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 43
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário mantendo seu próprio documento")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário mantendo seu próprio documento")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void AtualizarFuncionarioMantendoSeuProprioDocumento()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário mantendo seu próprio documento", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 47
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 48
    testRunner.And("que existe um funcionário cadastrado com ID conhecido e documento \"11111111111\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 49
    testRunner.When("o usuário atualiza o funcionário mantendo o documento \"11111111111\" e alterando o" +
                        "utros campos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 50
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 51
    testRunner.And("o funcionário deve ser atualizado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 52
    testRunner.And("o documento deve permanecer \"11111111111\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário com email duplicado de outro funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário com email duplicado de outro funcionário")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "conflito")]
        public void AtualizarFuncionarioComEmailDuplicadoDeOutroFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "conflito"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário com email duplicado de outro funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 56
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 57
    testRunner.And("que existe um funcionário com ID conhecido e email \"joao@supply.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 58
    testRunner.And("que existe outro funcionário com email \"maria@supply.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 59
    testRunner.When("o usuário tenta atualizar o funcionário para email \"maria@supply.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 60
    testRunner.Then("o sistema deve retornar status 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 61
    testRunner.And("o sistema deve retornar mensagem \"Email já cadastrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 62
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário para menor de idade")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário para menor de idade")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "negocio")]
        public void AtualizarFuncionarioParaMenorDeIdade()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "validacao",
                    "negocio"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário para menor de idade", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 66
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 67
    testRunner.And("que existe um funcionário cadastrado com ID conhecido e data de nascimento \"1990-" +
                        "01-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 68
    testRunner.When("o usuário tenta atualizar o funcionário com data de nascimento \"2010-06-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 69
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 70
    testRunner.And("o sistema deve retornar mensagem \"Employee must be at least 18 years old\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 71
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário removendo todos os telefones")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário removendo todos os telefones")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void AtualizarFuncionarioRemovendoTodosOsTelefones()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário removendo todos os telefones", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 75
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 76
    testRunner.And("que existe um funcionário cadastrado com ID conhecido e telefones \"11999999999,11" +
                        "888888888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 77
    testRunner.When("o usuário tenta atualizar o funcionário removendo todos os telefones", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 78
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 79
    testRunner.And("o sistema deve retornar mensagem \"Funcionário deve possuir pelo menos um telefone" +
                        "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 80
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário com gestor inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário com gestor inexistente")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void AtualizarFuncionarioComGestorInexistente()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário com gestor inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 84
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 85
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 86
    testRunner.And("que não existe gestor com ID \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 87
    testRunner.When("o usuário tenta atualizar o funcionário com gestor inexistente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 88
    testRunner.Then("o sistema deve retornar status 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 89
    testRunner.And("o sistema deve retornar mensagem \"Gestor não encontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 90
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário para ser seu próprio gestor")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário para ser seu próprio gestor")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "negocio")]
        public void AtualizarFuncionarioParaSerSeuProprioGestor()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "validacao",
                    "negocio"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário para ser seu próprio gestor", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 93
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 94
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 95
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 96
    testRunner.When("o usuário tenta atualizar o funcionário para ser seu próprio gestor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 97
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 98
    testRunner.And("o sistema deve retornar mensagem \"O funcionário não pode ser seu próprio gestor\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 99
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário com email inválido")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário com email inválido")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void AtualizarFuncionarioComEmailInvalido()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário com email inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 103
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 104
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 105
    testRunner.When("o usuário tenta atualizar o funcionário com email \"email-invalido\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 106
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 107
    testRunner.And("o sistema deve retornar mensagem indicando formato de email inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 108
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário com nome vazio")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário com nome vazio")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void AtualizarFuncionarioComNomeVazio()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário com nome vazio", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 111
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 112
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 113
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 114
    testRunner.When("o usuário tenta atualizar o funcionário com nome vazio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 115
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 116
    testRunner.And("o sistema deve retornar mensagem de erro indicando que nome é obrigatório", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 117
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualização deve invalidar cache do funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualização de Funcionário")]
        [Xunit.TraitAttribute("Description", "Atualização deve invalidar cache do funcionário")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "cache")]
        public void AtualizacaoDeveInvalidarCacheDoFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "atualizar",
                    "cache"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualização deve invalidar cache do funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 121
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 122
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 123
    testRunner.And("que os dados do funcionário estão em cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 124
    testRunner.When("o usuário atualiza o funcionário com dados válidos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 125
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 126
    testRunner.And("o cache do funcionário deve ser invalidado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AtualizacaoDeFuncionarioFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AtualizacaoDeFuncionarioFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
