// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AutenticacaoEAutorizacaoFeature : object, Xunit.IClassFixture<AutenticacaoEAutorizacaoFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Autenticacao.feature"
#line hidden
        
        public AutenticacaoEAutorizacaoFeature(AutenticacaoEAutorizacaoFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Autenticação e Autorização", "  Como um usuário do sistema\r\n  Eu quero me autenticar com minhas credenciais\r\n  " +
                    "Para acessar as funcionalidades protegidas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login bem-sucedido com credenciais válidas")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação e Autorização")]
        [Xunit.TraitAttribute("Description", "Login bem-sucedido com credenciais válidas")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void LoginBem_SucedidoComCredenciaisValidas()
        {
            string[] tagsOfScenario = new string[] {
                    "autenticacao",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login bem-sucedido com credenciais válidas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Senha"});
                table8.AddRow(new string[] {
                            "joao@supply.com",
                            "Senha@123456"});
#line 9
    testRunner.Given("que existe um funcionário cadastrado no sistema com:", ((string)(null)), table8, "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Senha"});
                table9.AddRow(new string[] {
                            "joao@supply.com",
                            "Senha@123456"});
#line 12
    testRunner.When("o usuário realiza login com:", ((string)(null)), table9, "Quando ");
#line hidden
#line 15
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 16
    testRunner.And("o sistema deve retornar um token JWT válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
    testRunner.And("o token deve conter as claims de identificação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 18
    testRunner.And("o token deve conter a claim de permissão do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login falha com email inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação e Autorização")]
        [Xunit.TraitAttribute("Description", "Login falha com email inexistente")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void LoginFalhaComEmailInexistente()
        {
            string[] tagsOfScenario = new string[] {
                    "autenticacao",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login falha com email inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
    testRunner.Given("que não existe um funcionário cadastrado com email \"inexistente@supply.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Senha"});
                table10.AddRow(new string[] {
                            "inexistente@supply.com",
                            "Senha@123456"});
#line 23
    testRunner.When("o usuário realiza login com:", ((string)(null)), table10, "Quando ");
#line hidden
#line 26
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 27
    testRunner.And("o sistema deve retornar mensagem \"Credenciais inválidas\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 28
    testRunner.And("o sistema não deve retornar token JWT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login falha com senha incorreta")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação e Autorização")]
        [Xunit.TraitAttribute("Description", "Login falha com senha incorreta")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void LoginFalhaComSenhaIncorreta()
        {
            string[] tagsOfScenario = new string[] {
                    "autenticacao",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login falha com senha incorreta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Senha"});
                table11.AddRow(new string[] {
                            "joao@supply.com",
                            "Senha@123456"});
#line 32
    testRunner.Given("que existe um funcionário cadastrado no sistema com:", ((string)(null)), table11, "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Senha"});
                table12.AddRow(new string[] {
                            "joao@supply.com",
                            "SenhaErrada"});
#line 35
    testRunner.When("o usuário realiza login com:", ((string)(null)), table12, "Quando ");
#line hidden
#line 38
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 39
    testRunner.And("o sistema deve retornar mensagem \"Credenciais inválidas\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 40
    testRunner.And("o sistema não deve retornar token JWT", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Acesso negado sem token de autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação e Autorização")]
        [Xunit.TraitAttribute("Description", "Acesso negado sem token de autenticação")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        [Xunit.TraitAttribute("Category", "seguranca")]
        public void AcessoNegadoSemTokenDeAutenticacao()
        {
            string[] tagsOfScenario = new string[] {
                    "autenticacao",
                    "seguranca"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Acesso negado sem token de autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 44
    testRunner.Given("que o usuário não possui token de autenticação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 45
    testRunner.When("o usuário tenta acessar o endpoint GET /api/employees", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 46
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 47
    testRunner.And("o sistema deve retornar mensagem \"Não autorizado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Acesso negado com token expirado")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação e Autorização")]
        [Xunit.TraitAttribute("Description", "Acesso negado com token expirado")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        [Xunit.TraitAttribute("Category", "seguranca")]
        public void AcessoNegadoComTokenExpirado()
        {
            string[] tagsOfScenario = new string[] {
                    "autenticacao",
                    "seguranca"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Acesso negado com token expirado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 51
    testRunner.Given("que o usuário possui um token JWT expirado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 52
    testRunner.When("o usuário tenta acessar o endpoint GET /api/employees", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 53
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 54
    testRunner.And("o sistema deve retornar mensagem \"Token expirado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Mensagem de erro genérica não revela existência de email")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação e Autorização")]
        [Xunit.TraitAttribute("Description", "Mensagem de erro genérica não revela existência de email")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        [Xunit.TraitAttribute("Category", "seguranca")]
        public void MensagemDeErroGenericaNaoRevelaExistenciaDeEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "autenticacao",
                    "seguranca"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mensagem de erro genérica não revela existência de email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Senha"});
                table13.AddRow(new string[] {
                            "joao@supply.com",
                            "Senha@123456"});
#line 58
    testRunner.Given("que existe um funcionário cadastrado no sistema com:", ((string)(null)), table13, "Dado ");
#line hidden
#line 61
    testRunner.When("o usuário realiza login com email \"joao@supply.com\" e senha \"SenhaErrada\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 62
    testRunner.Then("o sistema deve retornar mensagem \"Credenciais inválidas\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 63
    testRunner.When("o usuário realiza login com email \"naoexiste@supply.com\" e senha \"Qualquer123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 64
    testRunner.Then("o sistema deve retornar mensagem \"Credenciais inválidas\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AutenticacaoEAutorizacaoFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AutenticacaoEAutorizacaoFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
