// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CriacaoDeFuncionarioFeature : object, Xunit.IClassFixture<CriacaoDeFuncionarioFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CriarFuncionario.feature"
#line hidden
        
        public CriacaoDeFuncionarioFeature(CriacaoDeFuncionarioFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Criação de Funcionário", "  Como um usuário autorizado do sistema\r\n  Eu quero cadastrar novos funcionários\r" +
                    "\n  Para que eles possam acessar o sistema", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com dados válidos")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com dados válidos")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void CriarFuncionarioComDadosValidos()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com dados válidos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 10
    testRunner.And("que não existe funcionário com documento \"12345678900\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 11
    testRunner.And("que existe um gestor cadastrado com ID válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table14.AddRow(new string[] {
                            "João",
                            "Silva",
                            "joao@supply.com",
                            "12345678900",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "Senha@123456"});
#line 12
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table14, "Quando ");
#line hidden
#line 15
    testRunner.Then("o sistema deve retornar status 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 16
    testRunner.And("o sistema deve retornar os dados do funcionário criado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
    testRunner.And("o funcionário deve ter um ID único gerado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 18
    testRunner.And("a senha do funcionário deve estar hasheada no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com apenas um telefone")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com apenas um telefone")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void CriarFuncionarioComApenasUmTelefone()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com apenas um telefone", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 23
    testRunner.And("que não existe funcionário com documento \"12345678900\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table15.AddRow(new string[] {
                            "João",
                            "Silva",
                            "joao@supply.com",
                            "12345678900",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "Senha@123456"});
#line 24
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table15, "Quando ");
#line hidden
#line 27
    testRunner.Then("o sistema deve retornar status 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 28
    testRunner.And("o funcionário deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 29
    testRunner.And("o funcionário deve ter exatamente 1 telefone cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com múltiplos telefones")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com múltiplos telefones")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void CriarFuncionarioComMultiplosTelefones()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com múltiplos telefones", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 34
    testRunner.And("que não existe funcionário com documento \"12345678900\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Permissao",
                            "Senha"});
                table16.AddRow(new string[] {
                            "João",
                            "Silva",
                            "joao@supply.com",
                            "12345678900",
                            "1990-01-15",
                            "Employee",
                            "Senha@123456"});
#line 35
    testRunner.When("o usuário cria um novo funcionário com telefones:", ((string)(null)), table16, "Quando ");
#line hidden
#line 38
    testRunner.And("os telefones são \"11999999999,11888888888,11777777777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 39
    testRunner.Then("o sistema deve retornar status 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 40
    testRunner.And("o funcionário deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 41
    testRunner.And("o funcionário deve ter 3 telefones cadastrados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário sem autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário sem autenticação")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        public void CriarFuncionarioSemAutenticacao()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "autenticacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário sem autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 45
    testRunner.Given("que o usuário não está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 46
    testRunner.When("o usuário tenta criar um novo funcionário com dados válidos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 47
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 48
    testRunner.And("o sistema deve retornar mensagem \"Não autorizado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 49
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com nome vazio")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com nome vazio")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void CriarFuncionarioComNomeVazio()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com nome vazio", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 53
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table17.AddRow(new string[] {
                            "",
                            "Silva",
                            "joao@supply.com",
                            "12345678900",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "Senha@123456"});
#line 54
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table17, "Quando ");
#line hidden
#line 57
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 58
    testRunner.And("o sistema deve retornar mensagem de erro indicando que nome é obrigatório", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 59
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com sobrenome vazio")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com sobrenome vazio")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void CriarFuncionarioComSobrenomeVazio()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com sobrenome vazio", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 63
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table18.AddRow(new string[] {
                            "João",
                            "",
                            "joao@supply.com",
                            "12345678900",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "Senha@123456"});
#line 64
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table18, "Quando ");
#line hidden
#line 67
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 68
    testRunner.And("o sistema deve retornar mensagem de erro indicando que sobrenome é obrigatório", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 69
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com email inválido")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com email inválido")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void CriarFuncionarioComEmailInvalido()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com email inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 73
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table19.AddRow(new string[] {
                            "João",
                            "Silva",
                            "email-invalido",
                            "12345678900",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "Senha@123456"});
#line 74
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table19, "Quando ");
#line hidden
#line 77
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 78
    testRunner.And("o sistema deve retornar mensagem de erro indicando que email é inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 79
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com email vazio")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com email vazio")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void CriarFuncionarioComEmailVazio()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com email vazio", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 83
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table20.AddRow(new string[] {
                            "João",
                            "Silva",
                            "",
                            "12345678900",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "Senha@123456"});
#line 84
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table20, "Quando ");
#line hidden
#line 87
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 88
    testRunner.And("o sistema deve retornar mensagem de erro indicando que email é obrigatório", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 89
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com documento duplicado")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com documento duplicado")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "conflito")]
        public void CriarFuncionarioComDocumentoDuplicado()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "conflito"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com documento duplicado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 93
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 94
    testRunner.And("que já existe um funcionário cadastrado com documento \"12345678900\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table21.AddRow(new string[] {
                            "Maria",
                            "Santos",
                            "maria@supply.com",
                            "12345678900",
                            "1992-05-20",
                            "11777777777",
                            "Employee",
                            "Senha@123456"});
#line 95
    testRunner.When("o usuário tenta criar um novo funcionário com:", ((string)(null)), table21, "Quando ");
#line hidden
#line 98
    testRunner.Then("o sistema deve retornar status 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 99
    testRunner.And("o sistema deve retornar mensagem \"Document number already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 100
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com documento vazio")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com documento vazio")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void CriarFuncionarioComDocumentoVazio()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com documento vazio", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 103
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 104
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table22.AddRow(new string[] {
                            "João",
                            "Silva",
                            "joao@supply.com",
                            "",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "Senha@123456"});
#line 105
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table22, "Quando ");
#line hidden
#line 108
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 109
    testRunner.And("o sistema deve retornar mensagem de erro indicando que documento é obrigatório", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 110
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário menor de idade")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário menor de idade")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "negocio")]
        public void CriarFuncionarioMenorDeIdade()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao",
                    "negocio"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário menor de idade", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 114
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table23.AddRow(new string[] {
                            "Pedro",
                            "Costa",
                            "pedro@supply.com",
                            "98765432100",
                            "2010-06-15",
                            "11666666666",
                            "Employee",
                            "Senha@123456"});
#line 115
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table23, "Quando ");
#line hidden
#line 118
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 119
    testRunner.And("o sistema deve retornar mensagem \"Employee must be at least 18 years old\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 120
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário sem telefone")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário sem telefone")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void CriarFuncionarioSemTelefone()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário sem telefone", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 123
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 124
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Permissao",
                            "Senha"});
                table24.AddRow(new string[] {
                            "João",
                            "Silva",
                            "joao@supply.com",
                            "12345678900",
                            "1990-01-15",
                            "Employee",
                            "Senha@123456"});
#line 125
    testRunner.When("o usuário cria um novo funcionário sem telefones:", ((string)(null)), table24, "Quando ");
#line hidden
#line 128
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 129
    testRunner.And("o sistema deve retornar mensagem \"Funcionário deve possuir pelo menos um telefone" +
                        "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 130
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com email duplicado")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com email duplicado")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "conflito")]
        public void CriarFuncionarioComEmailDuplicado()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "conflito"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com email duplicado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 134
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 135
    testRunner.And("que já existe um funcionário cadastrado com email \"joao@supply.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table25.AddRow(new string[] {
                            "Outro",
                            "João",
                            "joao@supply.com",
                            "98765432100",
                            "1992-05-20",
                            "11777777777",
                            "Employee",
                            "Senha@123456"});
#line 136
    testRunner.When("o usuário tenta criar um novo funcionário com:", ((string)(null)), table25, "Quando ");
#line hidden
#line 139
    testRunner.Then("o sistema deve retornar status 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 140
    testRunner.And("o sistema deve retornar mensagem \"Email already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 141
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com gestor inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com gestor inexistente")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void CriarFuncionarioComGestorInexistente()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com gestor inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 144
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 145
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 146
    testRunner.And("que não existe gestor com ID \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table26.AddRow(new string[] {
                            "João",
                            "Silva",
                            "joao@supply.com",
                            "12345678900",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "Senha@123456"});
#line 147
    testRunner.When("o usuário tenta criar um novo funcionário com gestor inexistente:", ((string)(null)), table26, "Quando ");
#line hidden
#line 150
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 151
    testRunner.And("o sistema deve retornar mensagem \"Gestor não encontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 152
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com senha fraca")]
        [Xunit.TraitAttribute("FeatureTitle", "Criação de Funcionário")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com senha fraca")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "validacao")]
        public void CriarFuncionarioComSenhaFraca()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "criar",
                    "validacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com senha fraca", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 155
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 156
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome",
                            "Email",
                            "Documento",
                            "DataNascimento",
                            "Telefones",
                            "Permissao",
                            "Senha"});
                table27.AddRow(new string[] {
                            "João",
                            "Silva",
                            "joao@supply.com",
                            "12345678900",
                            "1990-01-15",
                            "11999999999",
                            "Employee",
                            "123"});
#line 157
    testRunner.When("o usuário cria um novo funcionário com:", ((string)(null)), table27, "Quando ");
#line hidden
#line 160
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 161
    testRunner.And("o sistema deve retornar mensagem indicando que a senha não atende aos critérios d" +
                        "e segurança", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 162
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CriacaoDeFuncionarioFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CriacaoDeFuncionarioFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
