// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ExclusaoDeFuncionarioFeature : object, Xunit.IClassFixture<ExclusaoDeFuncionarioFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ExcluirFuncionario.feature"
#line hidden
        
        public ExclusaoDeFuncionarioFeature(ExclusaoDeFuncionarioFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Exclusão de Funcionário", "  Como um usuário autorizado do sistema\r\n  Eu quero excluir funcionários\r\n  Para " +
                    "remover acessos de pessoas desligadas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Excluir funcionário com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Exclusão de Funcionário")]
        [Xunit.TraitAttribute("Description", "Excluir funcionário com sucesso")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void ExcluirFuncionarioComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "excluir",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Excluir funcionário com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 10
    testRunner.And("que existe um funcionário cadastrado com ID conhecido para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 11
    testRunner.When("o usuário exclui o funcionário através do endpoint DELETE /api/employees/{id}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 12
    testRunner.Then("o sistema deve retornar status 204", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 13
    testRunner.And("o funcionário deve ser marcado como excluído (soft delete)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 14
    testRunner.And("a data de exclusão deve ser registrada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Excluir funcionário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Exclusão de Funcionário")]
        [Xunit.TraitAttribute("Description", "Excluir funcionário inexistente")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void ExcluirFuncionarioInexistente()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "excluir",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Excluir funcionário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 19
    testRunner.And("que não existe funcionário com ID \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 20
    testRunner.When("o usuário tenta excluir o funcionário inexistente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 21
    testRunner.Then("o sistema deve retornar status 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 22
    testRunner.And("o sistema deve retornar mensagem \"Funcionário não encontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Excluir funcionário sem autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Exclusão de Funcionário")]
        [Xunit.TraitAttribute("Description", "Excluir funcionário sem autenticação")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        public void ExcluirFuncionarioSemAutenticacao()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "excluir",
                    "autenticacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Excluir funcionário sem autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
    testRunner.Given("que o usuário não está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 27
    testRunner.And("que existe um funcionário cadastrado com ID conhecido para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 28
    testRunner.When("o usuário tenta excluir o funcionário sem autenticação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 29
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 30
    testRunner.And("o sistema deve retornar mensagem \"Não autorizado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 31
    testRunner.And("o funcionário não deve ser excluído do banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Funcionário sem permissão tenta excluir outro funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Exclusão de Funcionário")]
        [Xunit.TraitAttribute("Description", "Funcionário sem permissão tenta excluir outro funcionário")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "autorizacao")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        public void FuncionarioSemPermissaoTentaExcluirOutroFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "excluir",
                    "autorizacao",
                    "hierarquia"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Funcionário sem permissão tenta excluir outro funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 35
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 36
    testRunner.And("que existe um funcionário cadastrado com ID conhecido para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 37
    testRunner.When("o usuário tenta excluir o funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 38
    testRunner.Then("o sistema deve retornar status 403", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 39
    testRunner.And("o sistema deve retornar mensagem \"Você não tem permissão para excluir funcionário" +
                        "s\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 40
    testRunner.And("o funcionário não deve ser excluído do banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Excluir funcionário que é gestor de outros")]
        [Xunit.TraitAttribute("FeatureTitle", "Exclusão de Funcionário")]
        [Xunit.TraitAttribute("Description", "Excluir funcionário que é gestor de outros")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "negocio")]
        public void ExcluirFuncionarioQueEGestorDeOutros()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "excluir",
                    "negocio"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Excluir funcionário que é gestor de outros", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 44
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 45
    testRunner.And("que existe um funcionário cadastrado com ID conhecido que é gestor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 46
    testRunner.And("que existem funcionários subordinados a este gestor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 47
    testRunner.When("o usuário tenta excluir o funcionário gestor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 48
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 49
    testRunner.And("o sistema deve retornar mensagem \"Não é possível excluir funcionário que possui s" +
                        "ubordinados\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 50
    testRunner.And("o funcionário não deve ser excluído do banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Exclusão deve invalidar cache")]
        [Xunit.TraitAttribute("FeatureTitle", "Exclusão de Funcionário")]
        [Xunit.TraitAttribute("Description", "Exclusão deve invalidar cache")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "cache")]
        public void ExclusaoDeveInvalidarCache()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "excluir",
                    "cache"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Exclusão deve invalidar cache", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 54
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 55
    testRunner.And("que existe um funcionário cadastrado com ID conhecido para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 56
    testRunner.And("que os dados do funcionário estão em cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 57
    testRunner.When("o usuário exclui o funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 58
    testRunner.Then("o sistema deve retornar status 204", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 59
    testRunner.And("o cache do funcionário deve ser invalidado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 60
    testRunner.And("o cache da lista de funcionários deve ser invalidado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Funcionário excluído não aparece em listagens")]
        [Xunit.TraitAttribute("FeatureTitle", "Exclusão de Funcionário")]
        [Xunit.TraitAttribute("Description", "Funcionário excluído não aparece em listagens")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "softdelete")]
        public void FuncionarioExcluidoNaoApareceEmListagens()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "excluir",
                    "softdelete"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Funcionário excluído não aparece em listagens", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 64
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 65
    testRunner.And("que existe um funcionário cadastrado com ID conhecido para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 66
    testRunner.When("o usuário exclui o funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 67
    testRunner.And("o usuário solicita a listagem de funcionários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 68
    testRunner.Then("o funcionário excluído não deve aparecer na listagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Soft delete preserva dados no banco")]
        [Xunit.TraitAttribute("FeatureTitle", "Exclusão de Funcionário")]
        [Xunit.TraitAttribute("Description", "Soft delete preserva dados no banco")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "softdelete")]
        public void SoftDeletePreservaDadosNoBanco()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "excluir",
                    "softdelete"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Soft delete preserva dados no banco", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 72
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 73
    testRunner.And("que existe um funcionário cadastrado com ID conhecido para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 74
    testRunner.When("o usuário exclui o funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 75
    testRunner.Then("o sistema deve retornar status 204", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 76
    testRunner.And("o registro do funcionário deve existir no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 77
    testRunner.And("o campo IsDeleted deve ser true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 78
    testRunner.And("o campo DeletedAt deve estar preenchido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ExclusaoDeFuncionarioFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ExclusaoDeFuncionarioFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
