// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class HierarquiaDePermissoesFeature : object, Xunit.IClassFixture<HierarquiaDePermissoesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "HierarquiaPermissoes.feature"
#line hidden
        
        public HierarquiaDePermissoesFeature(HierarquiaDePermissoesFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Hierarquia de Permissões", "  Como um Directoristrador do sistema\r\n  Eu quero garantir que a hierarquia de pe" +
                    "rmissões seja respeitada\r\n  Para manter a segurança e governança do sistema", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Admin pode criar qualquer nível de permissão")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Admin pode criar qualquer nível de permissão")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void AdminPodeCriarQualquerNivelDePermissao()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "criar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Admin pode criar qualquer nível de permissão", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    testRunner.Given("que o usuário está autenticado como \"Admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 12
    testRunner.When("o usuário cria um novo funcionário com permissão \"Admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 13
    testRunner.Then("o funcionário deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 14
    testRunner.And("o funcionário deve ter permissão \"Admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Director pode criar Leader")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Director pode criar Leader")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void DirectorPodeCriarLeader()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "criar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Director pode criar Leader", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 19
    testRunner.When("o usuário cria um novo funcionário com permissão \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 20
    testRunner.Then("o funcionário deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 21
    testRunner.And("o funcionário deve ter permissão \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Director pode criar Employee")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Director pode criar Employee")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void DirectorPodeCriarEmployee()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "criar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Director pode criar Employee", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 25
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 26
    testRunner.When("o usuário cria um novo funcionário com permissão \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 27
    testRunner.Then("o funcionário deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 28
    testRunner.And("o funcionário deve ter permissão \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Leader pode criar Employee")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Leader pode criar Employee")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void LeaderPodeCriarEmployee()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "criar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Leader pode criar Employee", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
    testRunner.Given("que o usuário está autenticado como \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 33
    testRunner.When("o usuário cria um novo funcionário com permissão \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 34
    testRunner.Then("o funcionário deve ser criado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 35
    testRunner.And("o funcionário deve ter permissão \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Leader não pode criar Director")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Leader não pode criar Director")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void LeaderNaoPodeCriarDirector()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "criar",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Leader não pode criar Director", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 39
    testRunner.Given("que o usuário está autenticado como \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 40
    testRunner.When("o usuário tenta criar um novo funcionário com permissão \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 41
    testRunner.Then("o sistema deve retornar status 403", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 42
    testRunner.And("o sistema deve retornar mensagem \"Você não pode criar um funcionário com permissã" +
                        "o igual ou superior à sua\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 43
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Leader não pode criar Leader")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Leader não pode criar Leader")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void LeaderNaoPodeCriarLeader()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "criar",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Leader não pode criar Leader", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 47
    testRunner.Given("que o usuário está autenticado como \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 48
    testRunner.When("o usuário tenta criar um novo funcionário com permissão \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 49
    testRunner.Then("o sistema deve retornar status 403", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 50
    testRunner.And("o sistema deve retornar mensagem \"Você não pode criar um funcionário com permissã" +
                        "o igual ou superior à sua\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 51
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Employee não pode criar nenhum funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Employee não pode criar nenhum funcionário")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "criar")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void EmployeeNaoPodeCriarNenhumFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "criar",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Employee não pode criar nenhum funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 55
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 56
    testRunner.When("o usuário tenta criar um novo funcionário com permissão \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 57
    testRunner.Then("o sistema deve retornar status 403", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 58
    testRunner.And("o sistema deve retornar mensagem \"Você não pode criar um funcionário com permissã" +
                        "o igual ou superior à sua\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 59
    testRunner.And("o funcionário não deve ser criado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Leader não pode promover Employee para Director")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Leader não pode promover Employee para Director")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void LeaderNaoPodePromoverEmployeeParaDirector()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "atualizar",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Leader não pode promover Employee para Director", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 63
    testRunner.Given("que o usuário está autenticado como \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 64
    testRunner.And("que existe um funcionário com permissão \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 65
    testRunner.When("o usuário tenta atualizar o funcionário para permissão \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 66
    testRunner.Then("o sistema deve retornar status 403", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 67
    testRunner.And("o sistema deve retornar mensagem \"Você não tem permissão para alterar usuários pa" +
                        "ra nível de permissão superior\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 68
    testRunner.And("o funcionário não deve ser atualizado no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Admin pode alterar qualquer permissão")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Admin pode alterar qualquer permissão")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void AdminPodeAlterarQualquerPermissao()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "atualizar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Admin pode alterar qualquer permissão", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 72
    testRunner.Given("que o usuário está autenticado como \"Admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 73
    testRunner.And("que existe um funcionário com permissão \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 74
    testRunner.When("o usuário atualiza o funcionário para permissão \"Admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 75
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 76
    testRunner.And("o funcionário deve ter permissão \"Admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Employee não pode excluir outros funcionários")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Employee não pode excluir outros funcionários")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void EmployeeNaoPodeExcluirOutrosFuncionarios()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "excluir",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Employee não pode excluir outros funcionários", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 80
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 81
    testRunner.And("que existe um funcionário cadastrado para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 82
    testRunner.When("o usuário tenta excluir o funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 83
    testRunner.Then("o sistema deve retornar status 403", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 84
    testRunner.And("o sistema deve retornar mensagem \"Você não tem permissão para excluir funcionário" +
                        "s\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Director pode excluir Employee")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Director pode excluir Employee")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void DirectorPodeExcluirEmployee()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "excluir",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Director pode excluir Employee", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 88
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 89
    testRunner.And("que existe um funcionário com permissão \"Employee\" para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 90
    testRunner.When("o usuário exclui o funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 91
    testRunner.Then("o sistema deve retornar status 204", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 92
    testRunner.And("o funcionário deve ser marcado como excluído", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Director pode excluir qualquer funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Hierarquia de Permissões")]
        [Xunit.TraitAttribute("Description", "Director pode excluir qualquer funcionário")]
        [Xunit.TraitAttribute("Category", "hierarquia")]
        [Xunit.TraitAttribute("Category", "excluir")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void DirectorPodeExcluirQualquerFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "hierarquia",
                    "excluir",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Director pode excluir qualquer funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 96
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 97
    testRunner.And("que existe um funcionário com permissão \"Director\" para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 98
    testRunner.When("o usuário exclui o funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 99
    testRunner.Then("o sistema deve retornar status 204", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 100
    testRunner.And("o funcionário deve ser marcado como excluído", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                HierarquiaDePermissoesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                HierarquiaDePermissoesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
