// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ListagemDeFuncionariosFeature : object, Xunit.IClassFixture<ListagemDeFuncionariosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ListarFuncionarios.feature"
#line hidden
        
        public ListagemDeFuncionariosFeature(ListagemDeFuncionariosFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Listagem de Funcionários", "  Como um usuário autenticado do sistema\r\n  Eu quero listar e buscar funcionários" +
                    "\r\n  Para visualizar as informações cadastradas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar todos os funcionários")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar todos os funcionários")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "listar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void ListarTodosOsFuncionarios()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "listar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar todos os funcionários", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 10
    testRunner.And("que existem 5 funcionários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 11
    testRunner.When("o usuário solicita a listagem de funcionários através do endpoint GET /api/employ" +
                        "ees", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 12
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 13
    testRunner.And("o sistema deve retornar uma lista com 5 funcionários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 14
    testRunner.And("cada funcionário na lista deve conter: ID, Nome, Sobrenome, Email, Documento, Tel" +
                        "efones, Permissao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
    testRunner.And("a senha não deve estar presente na resposta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar funcionários com paginação")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar funcionários com paginação")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "listar")]
        [Xunit.TraitAttribute("Category", "paginacao")]
        public void ListarFuncionariosComPaginacao()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "listar",
                    "paginacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar funcionários com paginação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 20
    testRunner.And("que existem 25 funcionários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "Page",
                            "PageSize"});
                table27.AddRow(new string[] {
                            "1",
                            "10"});
#line 21
    testRunner.When("o usuário solicita a listagem de funcionários com:", ((string)(null)), table27, "Quando ");
#line hidden
#line 24
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 25
    testRunner.And("o sistema deve retornar 10 funcionários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 26
    testRunner.And("a resposta deve conter informações de paginação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar segunda página de funcionários")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar segunda página de funcionários")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "listar")]
        [Xunit.TraitAttribute("Category", "paginacao")]
        public void ListarSegundaPaginaDeFuncionarios()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "listar",
                    "paginacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar segunda página de funcionários", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 30
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 31
    testRunner.And("que existem 25 funcionários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Page",
                            "PageSize"});
                table28.AddRow(new string[] {
                            "2",
                            "10"});
#line 32
    testRunner.When("o usuário solicita a listagem de funcionários com:", ((string)(null)), table28, "Quando ");
#line hidden
#line 35
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 36
    testRunner.And("o sistema deve retornar 10 funcionários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 37
    testRunner.And("os funcionários devem ser diferentes da primeira página", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar funcionários com filtro por nome")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar funcionários com filtro por nome")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "listar")]
        [Xunit.TraitAttribute("Category", "filtro")]
        public void ListarFuncionariosComFiltroPorNome()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "listar",
                    "filtro"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar funcionários com filtro por nome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 41
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Sobrenome"});
                table29.AddRow(new string[] {
                            "João",
                            "Silva"});
                table29.AddRow(new string[] {
                            "Maria",
                            "Santos"});
                table29.AddRow(new string[] {
                            "João",
                            "Costa"});
#line 42
    testRunner.And("que existem funcionários cadastrados:", ((string)(null)), table29, "E ");
#line hidden
#line 47
    testRunner.When("o usuário solicita a listagem de funcionários com filtro por nome \"João\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 48
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 49
    testRunner.And("o sistema deve retornar apenas funcionários cujo nome contenha \"João\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 50
    testRunner.And("a lista deve conter pelo menos 2 funcionários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar funcionários com filtro por email")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar funcionários com filtro por email")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "listar")]
        [Xunit.TraitAttribute("Category", "filtro")]
        public void ListarFuncionariosComFiltroPorEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "listar",
                    "filtro"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar funcionários com filtro por email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 54
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email"});
                table30.AddRow(new string[] {
                            "joao@supply.com"});
                table30.AddRow(new string[] {
                            "maria@supply.com"});
                table30.AddRow(new string[] {
                            "pedro@supply.com"});
#line 55
    testRunner.And("que existem funcionários cadastrados:", ((string)(null)), table30, "E ");
#line hidden
#line 60
    testRunner.When("o usuário solicita a listagem de funcionários com filtro por email \"joao@supply.c" +
                        "om\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 61
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 62
    testRunner.And("o sistema deve retornar apenas funcionários com email \"joao@supply.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 63
    testRunner.And("a lista deve conter exatamente 1 funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar funcionários com filtro por permissão")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar funcionários com filtro por permissão")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "listar")]
        [Xunit.TraitAttribute("Category", "filtro")]
        public void ListarFuncionariosComFiltroPorPermissao()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "listar",
                    "filtro"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar funcionários com filtro por permissão", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 67
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome",
                            "Permissao"});
                table31.AddRow(new string[] {
                            "João",
                            "Employee"});
                table31.AddRow(new string[] {
                            "Maria",
                            "Leader"});
                table31.AddRow(new string[] {
                            "Pedro",
                            "Director"});
#line 68
    testRunner.And("que existem funcionários cadastrados:", ((string)(null)), table31, "E ");
#line hidden
#line 73
    testRunner.When("o usuário solicita a listagem de funcionários com filtro por permissão \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 74
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 75
    testRunner.And("o sistema deve retornar apenas funcionários com permissão \"Leader\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar funcionário por ID existente")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Buscar funcionário por ID existente")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "buscar")]
        [Xunit.TraitAttribute("Category", "sucesso")]
        public void BuscarFuncionarioPorIDExistente()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "buscar",
                    "sucesso"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar funcionário por ID existente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 79
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 80
    testRunner.And("que existe um funcionário cadastrado com ID conhecido e nome \"João Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 81
    testRunner.When("o usuário solicita os dados do funcionário através do endpoint GET /api/employees" +
                        "/{id}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 82
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 83
    testRunner.And("o sistema deve retornar os dados completos do funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 84
    testRunner.And("a resposta deve conter: ID, Nome, Sobrenome, Email, Documento, Telefones, Permiss" +
                        "ao", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 85
    testRunner.And("a senha não deve estar presente na resposta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar funcionário por ID inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Buscar funcionário por ID inexistente")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "buscar")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void BuscarFuncionarioPorIDInexistente()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "buscar",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar funcionário por ID inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 89
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 90
    testRunner.And("que não existe funcionário com ID \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 91
    testRunner.When("o usuário solicita os dados do funcionário através do endpoint GET /api/employees" +
                        "/{id}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 92
    testRunner.Then("o sistema deve retornar status 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 93
    testRunner.And("o sistema deve retornar mensagem \"Funcionário não encontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar funcionários sem autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar funcionários sem autenticação")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "listar")]
        [Xunit.TraitAttribute("Category", "autenticacao")]
        public void ListarFuncionariosSemAutenticacao()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "listar",
                    "autenticacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar funcionários sem autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 97
    testRunner.Given("que o usuário não está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 98
    testRunner.When("o usuário tenta listar funcionários através do endpoint GET /api/employees", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 99
    testRunner.Then("o sistema deve retornar status 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 100
    testRunner.And("o sistema deve retornar mensagem \"Não autorizado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar funcionário deve usar cache quando disponível")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Buscar funcionário deve usar cache quando disponível")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "buscar")]
        [Xunit.TraitAttribute("Category", "cache")]
        public void BuscarFuncionarioDeveUsarCacheQuandoDisponivel()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "buscar",
                    "cache"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar funcionário deve usar cache quando disponível", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 103
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 104
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 105
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 106
    testRunner.And("que os dados do funcionário estão em cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 107
    testRunner.When("o usuário solicita os dados do funcionário através do endpoint GET /api/employees" +
                        "/{id}", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 108
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 109
    testRunner.And("os dados devem ser recuperados do cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 110
    testRunner.And("o banco de dados não deve ser consultado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar funcionários ordenados por nome")]
        [Xunit.TraitAttribute("FeatureTitle", "Listagem de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar funcionários ordenados por nome")]
        [Xunit.TraitAttribute("Category", "funcionario")]
        [Xunit.TraitAttribute("Category", "listar")]
        [Xunit.TraitAttribute("Category", "ordenacao")]
        public void ListarFuncionariosOrdenadosPorNome()
        {
            string[] tagsOfScenario = new string[] {
                    "funcionario",
                    "listar",
                    "ordenacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar funcionários ordenados por nome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 114
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nome"});
                table32.AddRow(new string[] {
                            "Carlos"});
                table32.AddRow(new string[] {
                            "Ana"});
                table32.AddRow(new string[] {
                            "Bruno"});
#line 115
    testRunner.And("que existem funcionários cadastrados:", ((string)(null)), table32, "E ");
#line hidden
#line 120
    testRunner.When("o usuário solicita a listagem de funcionários ordenada por nome ascendente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 121
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 122
    testRunner.And("os funcionários devem estar ordenados alfabeticamente por nome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ListagemDeFuncionariosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ListagemDeFuncionariosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
