// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class LoggingEAuditoriaFeature : object, Xunit.IClassFixture<LoggingEAuditoriaFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "LoggingAuditoria.feature"
#line hidden
        
        public LoggingEAuditoriaFeature(LoggingEAuditoriaFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Logging e Auditoria", "  Como um administrador do sistema\r\n  Eu quero que todas as operações sejam regis" +
                    "tradas em log\r\n  Para garantir rastreabilidade e auditoria", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar log ao criar funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Registrar log ao criar funcionário")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "criar")]
        public void RegistrarLogAoCriarFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "logging",
                    "criar"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registrar log ao criar funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 10
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 11
    testRunner.When("o usuário cria um novo funcionário com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 12
    testRunner.Then("o sistema deve registrar um log com nível \"Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 13
    testRunner.And("o log deve conter a operação realizada \"CreateEmployee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 14
    testRunner.And("o log deve conter o ID do usuário que executou a operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
    testRunner.And("o log deve conter o ID do funcionário criado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.And("o log deve conter timestamp da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar log ao atualizar funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Registrar log ao atualizar funcionário")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "atualizar")]
        public void RegistrarLogAoAtualizarFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "logging",
                    "atualizar"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registrar log ao atualizar funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 21
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 22
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 23
    testRunner.When("o usuário atualiza o funcionário com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 24
    testRunner.Then("o sistema deve registrar um log com nível \"Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 25
    testRunner.And("o log deve conter a operação realizada \"UpdateEmployee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 26
    testRunner.And("o log deve conter o ID do funcionário atualizado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 27
    testRunner.And("o log deve conter os campos alterados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 28
    testRunner.And("o log deve conter timestamp da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar log ao excluir funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Registrar log ao excluir funcionário")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "excluir")]
        public void RegistrarLogAoExcluirFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "logging",
                    "excluir"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registrar log ao excluir funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 33
    testRunner.And("que existe um funcionário cadastrado para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 34
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 35
    testRunner.When("o usuário exclui o funcionário com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 36
    testRunner.Then("o sistema deve registrar um log com nível \"Warning\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 37
    testRunner.And("o log deve conter a operação realizada \"DeleteEmployee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 38
    testRunner.And("o log deve conter o ID do funcionário excluído", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 39
    testRunner.And("o log deve conter timestamp da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar log de tentativa de acesso não autorizado")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Registrar log de tentativa de acesso não autorizado")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "seguranca")]
        public void RegistrarLogDeTentativaDeAcessoNaoAutorizado()
        {
            string[] tagsOfScenario = new string[] {
                    "logging",
                    "seguranca"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registrar log de tentativa de acesso não autorizado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 43
    testRunner.Given("que o usuário não está autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 44
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 45
    testRunner.When("o usuário tenta acessar um endpoint protegido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 46
    testRunner.Then("o sistema deve registrar um log com nível \"Warning\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 47
    testRunner.And("o log deve conter \"Unauthorized access attempt\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 48
    testRunner.And("o log deve conter o endpoint acessado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 49
    testRunner.And("o log deve conter timestamp da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar log de login bem-sucedido")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Registrar log de login bem-sucedido")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "login")]
        public void RegistrarLogDeLoginBem_Sucedido()
        {
            string[] tagsOfScenario = new string[] {
                    "logging",
                    "login"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registrar log de login bem-sucedido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 53
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "a@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 54
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 55
    testRunner.When("o usuário realiza login com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 56
    testRunner.Then("o sistema deve registrar um log com nível \"Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 57
    testRunner.And("o log deve conter \"Login successful\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 58
    testRunner.And("o log deve conter o email do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 59
    testRunner.And("o log deve conter timestamp da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar log de tentativa de login falha")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Registrar log de tentativa de login falha")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "login")]
        [Xunit.TraitAttribute("Category", "falha")]
        public void RegistrarLogDeTentativaDeLoginFalha()
        {
            string[] tagsOfScenario = new string[] {
                    "logging",
                    "login",
                    "falha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registrar log de tentativa de login falha", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 63
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "a@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 64
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 65
    testRunner.When("o usuário tenta fazer login com senha incorreta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 66
    testRunner.Then("o sistema deve registrar um log com nível \"Warning\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 67
    testRunner.And("o log deve conter \"Login failed\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 68
    testRunner.And("o log deve conter o email tentado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 69
    testRunner.And("o log deve conter timestamp da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar log ao alterar senha")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Registrar log ao alterar senha")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "senha")]
        public void RegistrarLogAoAlterarSenha()
        {
            string[] tagsOfScenario = new string[] {
                    "logging",
                    "senha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registrar log ao alterar senha", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 73
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "aAtual@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 74
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 75
    testRunner.When("o funcionário altera sua senha com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 76
    testRunner.Then("o sistema deve registrar um log com nível \"Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 77
    testRunner.And("o log deve conter \"Credentials updated\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 78
    testRunner.And("o log deve conter o ID do funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 79
    testRunner.And("o log deve conter timestamp da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 80
    testRunner.And("o log NÃO deve conter a senha antiga ou nova", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrar log de erro interno")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Registrar log de erro interno")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "erro")]
        public void RegistrarLogDeErroInterno()
        {
            string[] tagsOfScenario = new string[] {
                    "logging",
                    "erro"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Registrar log de erro interno", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 84
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 85
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 86
    testRunner.When("ocorre um erro interno durante uma operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 87
    testRunner.Then("o sistema deve registrar um log com nível \"Error\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 88
    testRunner.And("o log deve conter a stack trace do erro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 89
    testRunner.And("o log deve conter o contexto da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 90
    testRunner.And("o log deve conter timestamp da operação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Manter histórico de alterações do funcionário")]
        [Xunit.TraitAttribute("FeatureTitle", "Logging e Auditoria")]
        [Xunit.TraitAttribute("Description", "Manter histórico de alterações do funcionário")]
        [Xunit.TraitAttribute("Category", "auditoria")]
        [Xunit.TraitAttribute("Category", "historico")]
        public void ManterHistoricoDeAlteracoesDoFuncionario()
        {
            string[] tagsOfScenario = new string[] {
                    "auditoria",
                    "historico"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Manter histórico de alterações do funcionário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 93
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 94
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 95
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 96
    testRunner.And("que o sistema de logging está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 97
    testRunner.When("o usuário atualiza o nome do funcionário de \"João\" para \"Carlos\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 98
    testRunner.Then("o sistema deve registrar a alteração no histórico de auditoria", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 99
    testRunner.And("o histórico deve conter o valor anterior \"João\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 100
    testRunner.And("o histórico deve conter o novo valor \"Carlos\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 101
    testRunner.And("o histórico deve conter o usuário que fez a alteração", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 102
    testRunner.And("o histórico deve conter a data da alteração", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                LoggingEAuditoriaFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                LoggingEAuditoriaFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
