// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PerformanceEEscalabilidadeFeature : object, Xunit.IClassFixture<PerformanceEEscalabilidadeFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PerformanceEscalabilidade.feature"
#line hidden
        
        public PerformanceEEscalabilidadeFeature(PerformanceEEscalabilidadeFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Performance e Escalabilidade", "  Como um sistema de produção\r\n  Eu quero garantir tempos de resposta adequados\r\n" +
                    "  Para proporcionar boa experiência ao usuário", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar funcionários com grande volume de dados")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Listar funcionários com grande volume de dados")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "listagem")]
        public void ListarFuncionariosComGrandeVolumeDeDados()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "listagem"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar funcionários com grande volume de dados", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 10
    testRunner.And("que existem 1000 funcionários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 11
    testRunner.When("o usuário solicita a listagem de funcionários com paginação de 10 por página", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 12
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 13
    testRunner.And("o tempo de resposta deve ser menor que 500ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 14
    testRunner.And("o sistema deve retornar apenas 10 funcionários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
    testRunner.And("a resposta deve incluir informações de paginação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar funcionário por ID com resposta rápida")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Buscar funcionário por ID com resposta rápida")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "busca")]
        public void BuscarFuncionarioPorIDComRespostaRapida()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "busca"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar funcionário por ID com resposta rápida", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 20
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 21
    testRunner.When("o usuário solicita os dados do funcionário por ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 22
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 23
    testRunner.And("o tempo de resposta deve ser menor que 200ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Busca por ID deve usar cache para melhorar performance")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Busca por ID deve usar cache para melhorar performance")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "cache")]
        public void BuscaPorIDDeveUsarCacheParaMelhorarPerformance()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "cache"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por ID deve usar cache para melhorar performance", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 27
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 28
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 29
    testRunner.And("que os dados estão em cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 30
    testRunner.When("o usuário solicita os dados do funcionário por ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 31
    testRunner.Then("o tempo de resposta deve ser menor que 50ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 32
    testRunner.And("os dados devem vir do cache", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 33
    testRunner.And("o banco de dados não deve ser consultado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar funcionários por nome com performance adequada")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Filtrar funcionários por nome com performance adequada")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "filtro")]
        public void FiltrarFuncionariosPorNomeComPerformanceAdequada()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "filtro"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Filtrar funcionários por nome com performance adequada", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 37
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 38
    testRunner.And("que existem 1000 funcionários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 39
    testRunner.When("o usuário filtra funcionários pelo nome \"João\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 40
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 41
    testRunner.And("o tempo de resposta deve ser menor que 300ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar funcionário com tempo de resposta adequado")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Criar funcionário com tempo de resposta adequado")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "criacao")]
        public void CriarFuncionarioComTempoDeRespostaAdequado()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "criacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar funcionário com tempo de resposta adequado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 45
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 46
    testRunner.When("o usuário cria um novo funcionário com dados válidos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 47
    testRunner.Then("o sistema deve retornar status 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 48
    testRunner.And("o tempo de resposta deve ser menor que 500ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 49
    testRunner.And("o hash da senha deve ser gerado de forma segura", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar funcionário com tempo de resposta adequado")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Atualizar funcionário com tempo de resposta adequado")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "atualizacao")]
        public void AtualizarFuncionarioComTempoDeRespostaAdequado()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "atualizacao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar funcionário com tempo de resposta adequado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 53
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 54
    testRunner.And("que existe um funcionário cadastrado com ID conhecido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 55
    testRunner.When("o usuário atualiza o funcionário com dados válidos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 56
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 57
    testRunner.And("o tempo de resposta deve ser menor que 300ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Excluir funcionário com tempo de resposta adequado")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Excluir funcionário com tempo de resposta adequado")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "exclusao")]
        public void ExcluirFuncionarioComTempoDeRespostaAdequado()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "exclusao"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Excluir funcionário com tempo de resposta adequado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 61
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 62
    testRunner.And("que existe um funcionário cadastrado para exclusão", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 63
    testRunner.When("o usuário exclui o funcionário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 64
    testRunner.Then("o sistema deve retornar status 204", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 65
    testRunner.And("o tempo de resposta deve ser menor que 200ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login deve ter tempo de resposta adequado")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Login deve ter tempo de resposta adequado")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "login")]
        public void LoginDeveTerTempoDeRespostaAdequado()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "login"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login deve ter tempo de resposta adequado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 69
    testRunner.Given("que existe um funcionário cadastrado com email \"usuario@supply.com\" e senha \"Senh" +
                        "a@123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 70
    testRunner.When("o usuário realiza login com credenciais válidas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 71
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 72
    testRunner.And("o tempo de resposta deve ser menor que 500ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 73
    testRunner.And("a verificação de senha deve usar algoritmo seguro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Sistema deve suportar múltiplas requisições simultâneas")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Sistema deve suportar múltiplas requisições simultâneas")]
        [Xunit.TraitAttribute("Category", "escalabilidade")]
        [Xunit.TraitAttribute("Category", "concorrencia")]
        public void SistemaDeveSuportarMultiplasRequisicoesSimultaneas()
        {
            string[] tagsOfScenario = new string[] {
                    "escalabilidade",
                    "concorrencia"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sistema deve suportar múltiplas requisições simultâneas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 77
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 78
    testRunner.And("que existem 100 funcionários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 79
    testRunner.When("50 usuários fazem requisições simultâneas de listagem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 80
    testRunner.Then("todas as requisições devem retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 81
    testRunner.And("nenhuma requisição deve exceder 2 segundos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listagem paginada deve ter uso eficiente de memória")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Listagem paginada deve ter uso eficiente de memória")]
        [Xunit.TraitAttribute("Category", "escalabilidade")]
        [Xunit.TraitAttribute("Category", "memoria")]
        public void ListagemPaginadaDeveTerUsoEficienteDeMemoria()
        {
            string[] tagsOfScenario = new string[] {
                    "escalabilidade",
                    "memoria"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listagem paginada deve ter uso eficiente de memória", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 85
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 86
    testRunner.And("que existem 10000 funcionários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 87
    testRunner.When("o usuário solicita a listagem com paginação de 20 por página", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 88
    testRunner.Then("o sistema deve carregar apenas os 20 registros solicitados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 89
    testRunner.And("o uso de memória deve permanecer estável", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Busca por email deve usar índice do banco de dados")]
        [Xunit.TraitAttribute("FeatureTitle", "Performance e Escalabilidade")]
        [Xunit.TraitAttribute("Description", "Busca por email deve usar índice do banco de dados")]
        [Xunit.TraitAttribute("Category", "performance")]
        [Xunit.TraitAttribute("Category", "indice")]
        public void BuscaPorEmailDeveUsarIndiceDoBancoDeDados()
        {
            string[] tagsOfScenario = new string[] {
                    "performance",
                    "indice"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Busca por email deve usar índice do banco de dados", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 93
    testRunner.Given("que o usuário está autenticado como \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 94
    testRunner.And("que existem 5000 funcionários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 95
    testRunner.When("o usuário busca funcionário por email \"joao@supply.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 96
    testRunner.Then("o sistema deve retornar status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 97
    testRunner.And("o tempo de resposta deve ser menor que 100ms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 98
    testRunner.And("a busca deve utilizar índice no campo email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PerformanceEEscalabilidadeFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PerformanceEEscalabilidadeFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
