// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EmployeeManagement.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ValidacoesDeCamposFeature : object, Xunit.IClassFixture<ValidacoesDeCamposFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Validacoes.feature"
#line hidden
        
        public ValidacoesDeCamposFeature(ValidacoesDeCamposFeature.FixtureData fixtureData, EmployeeManagement_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Validações de Campos", "  Como um sistema robusto\r\n  Eu quero validar todos os campos de entrada\r\n  Para " +
                    "garantir a integridade dos dados", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar formato de email inválido sem arroba")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar formato de email inválido sem arroba")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "email")]
        public void ValidarFormatoDeEmailInvalidoSemArroba()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "email"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar formato de email inválido sem arroba", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 10
    testRunner.When("o usuário tenta criar um funcionário com email \"email-sem-arroba\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 11
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 12
    testRunner.And("o sistema deve retornar mensagem indicando formato de email inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar formato de email inválido sem domínio")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar formato de email inválido sem domínio")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "email")]
        public void ValidarFormatoDeEmailInvalidoSemDominio()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "email"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar formato de email inválido sem domínio", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 16
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 17
    testRunner.When("o usuário tenta criar um funcionário com email \"usuario@\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 18
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 19
    testRunner.And("o sistema deve retornar mensagem indicando formato de email inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar formato de email inválido com espaços")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar formato de email inválido com espaços")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "email")]
        public void ValidarFormatoDeEmailInvalidoComEspacos()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "email"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar formato de email inválido com espaços", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 23
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 24
    testRunner.When("o usuário tenta criar um funcionário com email \"usuario @email.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 25
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 26
    testRunner.And("o sistema deve retornar mensagem indicando formato de email inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar formato de telefone muito curto")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar formato de telefone muito curto")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "telefone")]
        public void ValidarFormatoDeTelefoneMuitoCurto()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "telefone"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar formato de telefone muito curto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 30
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 31
    testRunner.When("o usuário tenta criar um funcionário com telefone \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 32
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 33
    testRunner.And("o sistema deve retornar mensagem indicando formato de telefone inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar formato de telefone com letras")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar formato de telefone com letras")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "telefone")]
        public void ValidarFormatoDeTelefoneComLetras()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "telefone"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar formato de telefone com letras", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 37
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 38
    testRunner.When("o usuário tenta criar um funcionário com telefone \"11ABCD99999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 39
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 40
    testRunner.And("o sistema deve retornar mensagem indicando formato de telefone inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar documento CPF com formato inválido")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar documento CPF com formato inválido")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "documento")]
        public void ValidarDocumentoCPFComFormatoInvalido()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "documento"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar documento CPF com formato inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 44
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 45
    testRunner.When("o usuário tenta criar um funcionário com documento \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 46
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 47
    testRunner.And("o sistema deve retornar mensagem indicando formato de documento inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar documento CPF com letras")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar documento CPF com letras")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "documento")]
        public void ValidarDocumentoCPFComLetras()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "documento"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar documento CPF com letras", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 51
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 52
    testRunner.When("o usuário tenta criar um funcionário com documento \"123ABC45678\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 53
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 54
    testRunner.And("o sistema deve retornar mensagem indicando formato de documento inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar documento CPF com todos dígitos iguais")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar documento CPF com todos dígitos iguais")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "documento")]
        public void ValidarDocumentoCPFComTodosDigitosIguais()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "documento"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar documento CPF com todos dígitos iguais", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 58
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 59
    testRunner.When("o usuário tenta criar um funcionário com documento \"11111111111\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 60
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 61
    testRunner.And("o sistema deve retornar mensagem indicando documento inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar senha muito curta")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar senha muito curta")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "senha")]
        public void ValidarSenhaMuitoCurta()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "senha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar senha muito curta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 65
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 66
    testRunner.When("o usuário tenta criar um funcionário com senha \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 67
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 68
    testRunner.And("o sistema deve retornar mensagem indicando que a senha é muito curta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar senha sem caracteres especiais")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar senha sem caracteres especiais")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "senha")]
        public void ValidarSenhaSemCaracteresEspeciais()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "senha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar senha sem caracteres especiais", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 72
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 73
    testRunner.When("o usuário tenta criar um funcionário com senha \"Senha123456\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 74
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 75
    testRunner.And("o sistema deve retornar mensagem indicando que a senha deve conter caracteres esp" +
                        "eciais", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar senha sem números")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar senha sem números")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "senha")]
        public void ValidarSenhaSemNumeros()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "senha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar senha sem números", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 79
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 80
    testRunner.When("o usuário tenta criar um funcionário com senha \"Senha@Forte\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 81
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 82
    testRunner.And("o sistema deve retornar mensagem indicando que a senha deve conter números", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar senha sem letras maiúsculas")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar senha sem letras maiúsculas")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "senha")]
        public void ValidarSenhaSemLetrasMaiusculas()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "senha"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar senha sem letras maiúsculas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 86
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 87
    testRunner.When("o usuário tenta criar um funcionário com senha \"senha@123456\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 88
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 89
    testRunner.And("o sistema deve retornar mensagem indicando que a senha deve conter letras maiúscu" +
                        "las", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar data de nascimento no futuro")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar data de nascimento no futuro")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "data")]
        public void ValidarDataDeNascimentoNoFuturo()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "data"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar data de nascimento no futuro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 93
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 94
    testRunner.When("o usuário tenta criar um funcionário com data de nascimento \"2030-01-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 95
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 96
    testRunner.And("o sistema deve retornar mensagem indicando data de nascimento inválida", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar data de nascimento muito antiga")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar data de nascimento muito antiga")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "data")]
        public void ValidarDataDeNascimentoMuitoAntiga()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "data"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar data de nascimento muito antiga", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 100
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 101
    testRunner.When("o usuário tenta criar um funcionário com data de nascimento \"1800-01-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 102
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 103
    testRunner.And("o sistema deve retornar mensagem indicando data de nascimento inválida", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar nome com números")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar nome com números")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "nome")]
        public void ValidarNomeComNumeros()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "nome"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar nome com números", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 107
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 108
    testRunner.When("o usuário tenta criar um funcionário com nome \"João123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 109
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 110
    testRunner.And("o sistema deve retornar mensagem indicando formato de nome inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar nome muito curto")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar nome muito curto")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "nome")]
        public void ValidarNomeMuitoCurto()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "nome"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar nome muito curto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 114
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 115
    testRunner.When("o usuário tenta criar um funcionário com nome \"A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 116
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 117
    testRunner.And("o sistema deve retornar mensagem indicando que o nome deve ter pelo menos 2 carac" +
                        "teres", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar sobrenome muito longo")]
        [Xunit.TraitAttribute("FeatureTitle", "Validações de Campos")]
        [Xunit.TraitAttribute("Description", "Validar sobrenome muito longo")]
        [Xunit.TraitAttribute("Category", "validacao")]
        [Xunit.TraitAttribute("Category", "nome")]
        public void ValidarSobrenomeMuitoLongo()
        {
            string[] tagsOfScenario = new string[] {
                    "validacao",
                    "nome"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar sobrenome muito longo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 121
    testRunner.Given("que o usuário está autenticado como \"Director\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 122
    testRunner.When("o usuário tenta criar um funcionário com sobrenome de 300 caracteres", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 123
    testRunner.Then("o sistema deve retornar status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 124
    testRunner.And("o sistema deve retornar mensagem indicando que o sobrenome excede o limite de car" +
                        "acteres", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ValidacoesDeCamposFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ValidacoesDeCamposFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
